namePrefix: "staging-"
resources:
  - gke.yaml
  - helm.yaml
  - kubernetes.yaml
  - providers.yaml

commonLabels:
  keptn.sh/stage: "staging"

patchesStrategicMerge:
  - provider-patch.yaml
  - cluster-patch.yaml
  - helm-patch.yaml
  - kubectl-patch.yaml