namePrefix: "dev-"
resources:
  - gke.yaml
  - helm.yaml
  - kubernetes.yaml
  - providers.yaml

patchesStrategicMerge:
  - provider-patch.yaml
  - cluster-patch.yaml
  - helm-patch.yaml
  - kubectl-patch.yaml